# Properties file for local environment
## Overrides application.yml default properties
#spring:
#  jpa:
#    show_sql: false
#
#app:
#  datasource:
#      jdbc-url: jdbc:mysql://localhost:3306/pedido}?stringtype=unspecified
#      username: root
#      password: root
#
#server:
#  port: 8180
